version: '3.6'
services:
  ssh:
    image: zalkeen/sftp:arm32v7
    volumes:
      - ${SSH_VOLUME_USERS:-./volumes/users}:/etc/sftp/users.conf:ro
      - ${SSH_VOLUME_HOSTKEY_ED2219:-./volumes/keys/hostkey-ed25519}:/etc/ssh/ssh_host_ed25519_key:ro
      - ${SSH_VOLUME_HOSTKEY_RSA:-./volumes/keys/hostkey-rsa}:/etc/ssh/ssh_host_rsa_key:ro
      - ${SSH_VOLUME_AUTOSTART:-./volumes/autostart}:/etc/sftp.d
      - ${GLOBAL_VOLUME_DATA:-./volumes/data}:/home
    ports:
      - ${SSH_PORT:-2244}:22
  http:
    image: nginx:stable
    volumes:
      - ${GLOBAL_VOLUME_DATA:-./volumes/data}:/usr/share/nginx/html
    networks:
      - web
      - default
    configs:
      - source: http
        target: /etc/nginx/conf.d/default.conf
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:${HTTP_CONF_URL:-share.domain.com}"
        - "traefik.frontend.port=80"
configs:
  http:
    file: ./volumes/http.conf
networks:
  web:
    external: true
